<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RimeSharp.PowerShell.ManagedTests</AssemblyName>
    <BaseOutputPath>..\..\obj\ManagedTests\bin\</BaseOutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RimeSharp.PowerShell.csproj" />
  </ItemGroup>

</Project>
